[mysqld]
basedir = "{{MYSQL_BASEDIR}}"
datadir = "{{MYSQL_DATADIR}}"
port = {{MYSQL_PORT}}
skip-networking = 0
bind-address = 127.0.0.1
# keep default Windows-friendly settings
sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
